tinycli_register("v",  f_v,  v)
tinycli_register("i",  f_i,  i)
tinycli_register("d",  f_d,  d)
tinycli_register("ii", f_ii, ii)
tinycli_register("id", f_id, id)
tinycli_register("di", f_di, di)
tinycli_register("dd", f_dd, dd)
