name: CI

on:
  push:         {branches: [ master ]}
  pull_request: {branches: [ master ]}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Unittests
        run: make -C $GITHUB_WORKSPACE/test/

  example-msp430:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile MSP430 Example
        run: |
         cd $GITHUB_WORKSPACE/examples/msp430/
         wget --no-verbose http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/8_3_2_2/export/msp430-gcc-8.3.1.25_linux64.tar.bz2
         wget --no-verbose http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/8_3_2_2/export/msp430-gcc-support-files-1.209.zip
         tar -xf msp430-gcc-8.3.1.25_linux64.tar.bz2 && mv msp430-gcc-8.3.1.25_linux64 msp430-gcc
         unzip -q msp430-gcc-support-files-1.209.zip
         make

