name: CI

on:
  push:         {branches: [ feature/ci ]}
  pull_request: {branches: [ feature/ci ]}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Unittests
        run: make -C $GITHUB_WORKSPACE/tinycli/test/
